version: '3.1'

services:
  jrtb:
    build:
      context: .

    network_mode: "host"
    environment:
      - BOT_NAME=javarush_RX_community_bot
      - BOT_TOKEN=8917055052:AAHyf7YKYXb56MFi-IyctQ8Hiwole_NUZ6I
    restart: always