services:
  jrtb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "dev_jrtb_db"
      MYSQL_USER: "dev_user"
      MYSQL_PASSWORD: "dev_jrtb_db_password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    expose:
      - '3307'